### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by themanjotsingh** [kiwicopple/sheetmetal.io#13]
Hello, seem to be having issues fully running the install, hoping that someone can lead me in the right direction

![image](https://user-images.githubusercontent.com/24256739/103371722-35a18c80-4a9e-11eb-8aab-5d5655caa399.png)

/root/.npm/_logs/2020-12-30T17_53_33_309Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'dev' ]
2 info using npm@6.14.10
3 info using node@v6.10.3
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle sheetmetal.io@0.0.2~predev: sheetmetal.io@0.0.2
6 info lifecycle sheetmetal.io@0.0.2~dev: sheetmetal.io@0.0.2
7 verbose lifecycle sheetmetal.io@0.0.2~dev: unsafe-perm in lifecycle true
8 verbose lifecycle sheetmetal.io@0.0.2~dev: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/sheetmetal.io/node_modules/.bin:/usr/local/sbin:/usr/local/$
9 verbose lifecycle sheetmetal.io@0.0.2~dev: CWD: /root/sheetmetal.io
10 silly lifecycle sheetmetal.io@0.0.2~dev: Args: [ '-c', 'NODE_ENV=local node server' ]
11 silly lifecycle sheetmetal.io@0.0.2~dev: Returned: code: 1  signal: null
12 info lifecycle sheetmetal.io@0.0.2~dev: Failed to exec dev script
13 verbose stack Error: sheetmetal.io@0.0.2 dev: `NODE_ENV=local node server`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at EventEmitter.emit (events.js:191:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:886:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
14 verbose pkgid sheetmetal.io@0.0.2
15 verbose cwd /root/sheetmetal.io
16 verbose Linux 4.15.0-128-generic
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
18 verbose node v6.10.3
19 verbose npm  v6.14.10
20 error code ELIFECYCLE
21 error errno 1
22 error sheetmetal.io@0.0.2 dev: `NODE_ENV=local node server`
22 error Exit status 1
23 error Failed at the sheetmetal.io@0.0.2 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

Thank you in advance

**Comment by kiwicopple** [comment]
Hey @themanjotsingh - this was just a sideproject. I don't think I ever actually finished it
